# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "graylog2_exceptions"
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lennart Koopmann"]
  s.date = "2014-03-27"
  s.description = "A Rack middleware that sends every Exception as GELF message to your Graylog2 server"
  s.email = "lennart@socketfeed.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
    "Rakefile",
    "VERSION",
    "graylog2_exceptions.gemspec",
    "lib/graylog2_exceptions.rb",
    "test/helper.rb",
    "test/test_graylog2_exceptions.rb"
  ]
  s.homepage = "http://www.graylog2.org/"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Graylog2 exception notifier"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gelf>, ["= 1.4.0"])
    else
      s.add_dependency(%q<gelf>, ["= 1.4.0"])
    end
  else
    s.add_dependency(%q<gelf>, ["= 1.4.0"])
  end
end

